# Generated by Django 5.0.1 on 2024-01-14 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_rename_meme_memetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.memetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MemeTextBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('box_number', models.IntegerField()),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_boxes', to='memes.meme')),
            ],
            options={
                'ordering': ['box_number'],
            },
        ),
    ]
