# Generated by Django 5.0.1 on 2024-01-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_meme_memetextbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='memetemplate',
            name='template_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
