# Generated by Django 5.0.1 on 2024-01-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0004_memetemplate_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
